# Etapa de construcción del frontend
FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa final para servir el frontend
FROM nginx:alpine

# Copia los archivos del build del frontend al contenedor de nginx
COPY --from=build /app/build /usr/share/nginx/html

# Expón el puerto en el que nginx servirá el frontend
EXPOSE 80

# Comando por defecto para nginx
CMD ["nginx", "-g", "daemon off;"]